---
#Install NGINX server
- name: "Install nginx via apt"
  ansible.builtin.apt:
    name: "nginx"
    state: "latest"
    update_cache: true
- name: "Delete /var/www/html folder"
  ansible.builtin.file:
    path: "/var/www/html"
    state: "absent"
- name: "Copy our landing to /var/www/html folder"
  ansible.builtin.copy:
    src: "files/html"
    dest: "/var/www"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"
- name: "Copy test landing to /var/www/html/test-site"
  ansible.builtin.copy:
    src: "files/test-site"
    dest: "/var/www/html"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"
- name: "Copy nginx config to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/sites-available/slurm.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Copy test site config to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/nginx-test.conf"
    dest: "/etc/nginx/sites-available/mytestsite.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Copy test site config to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/nginx-php.conf"
    dest: "/etc/nginx/sites-available/php-test.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Link folder for mytestsite.com"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/slurm.conf"
    dest: "/etc/nginx/sites-enabled/slurm"
    state: "link" # здесь создаем симлинк

- name: "Link folder"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/php-test.conf"
    dest: "/etc/nginx/sites-enabled/php-test"
    state: "link" # здесь создаем симлинк

- name: "Link folder for mytestsite.com"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/mytestsite.conf"
    dest: "/etc/nginx/sites-enabled/mytestsite"
    state: "link" # здесь создаем симлинк

...