# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.define "controlnode" do |controlnode|
  controlnode.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
	 vb.cpus = 1
   end
   controlnode.vm.box = "ubuntu2204-server-64bit"
   controlnode.vm.hostname = "controlnode"
   controlnode.vm.network "public_network", bridge: 'Realtek PCIe GbE Family Controller', ip: "192.168.0.110"
   controlnode.vm.synced_folder "./ansible","/home/vagrant/ansible"
   controlnode.vm.provision "shell", inline: <<-SHELL
     sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
     systemctl restart ssh
	 apt-add-repository ppa:ansible/ansible
	 apt update --yes
	 apt install -y htop
	 apt install -y ansible
	 ansible-galaxy collection install community.mysql
	 echo "[defaults]" >> /etc/ansible/ansible.cfg
	 echo "host_key_checking = False" >> /etc/ansible/ansible.cfg
   SHELL
 end
 # Every Vagrant development environment requires a box. You can search for
 # boxes at https://vagrantcloud.com/search.
 config.vm.define "server" do |server|
  server.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
	 vb.cpus = 1
   end
  server.vm.box = "ubuntu2204-server-64bit"
  server.vm.hostname = "server"
  server.vm.network "public_network", bridge: 'Realtek PCIe GbE Family Controller', ip: "192.168.0.111"
  server.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
    systemctl restart ssh
  SHELL
 end
end
