---
#Install NGINX server
- name: "Install nginx via yum"
  ansible.builtin.yum:
    name: "nginx"
    state: "latest"
    update_cache: true
- name: "Delete /var/www/html folder"
  ansible.builtin.file:
    path: "/var/www/html"
    state: "absent"
- name: "Copy our landing to /var/www/html folder"
  ansible.builtin.copy:
    src: "files/html"
    dest: "/var/www"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Copy test landing to /var/www/html/test-site"
  ansible.builtin.copy:
    src: "files/test-site"
    dest: "/var/www/html"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"


- name: "Create /etc/nginx/sites-available directory"
  ansible.builtin.file:
    path: "/etc/nginx/sites-available"
    state: "directory"
    mode: "0755"

- name: "Copy slurm config to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/slurm.conf"
    dest: "/etc/nginx/sites-available/slurm.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Copy nginx-test.conf to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/nginx-test.conf"
    dest: "/etc/nginx/sites-available/mytestsite.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Copy nginx php-config.conf to /etc/nginx/sites-available"
  ansible.builtin.copy:
    src: "files/nginx-php.conf"
    dest: "/etc/nginx/sites-available/php-test.conf"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"

- name: "Link folder for mytestsite.com"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/slurm.conf"
    dest: "/etc/nginx/conf.d/slurm"
    state: "link" # здесь создаем симлинк

- name: "Link folder"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/php-test.conf"
    dest: "/etc/nginx/conf.d/php-test"
    state: "link" # здесь создаем симлинк

- name: "Link folder for mytestsite.com"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/mytestsite.conf"
    dest: "/etc/nginx/conf.d/mytestsite"
    state: "link" # здесь создаем симлинк

- name: "Copy nginx configuration file"
  ansible.builtin.copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx"
    mode: "0644"

...